source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StyleSheet_Example', :exclusive => true do
  pod "StyleSheet", :path => "../"
end

target 'StyleSheet_Tests', :exclusive => true do
  pod "StyleSheet", :path => "../"

  
end
